### ISSUE TITLE
Use the Elasticsearch `uri_parts` ingest processor to parse URLs

### ISSUE THREAD

**Issue by dmathieu** [elastic/apm-data#101]
We should investigate whether we could use the Elasticsearch [`uri_parts`](https://www.elastic.co/guide/en/elasticsearch/reference/current/uri-parts-processor.html) ingest processor to parse URLs, and include only the full URL in the model types.

_Originally posted by @axw in https://github.com/elastic/apm-data/issues/47#issuecomment-1595630586_

**Comment by dmathieu** [comment]
I'm extracting this into a new issue, as it seems possibly medium size, and requires at least 2 PRs (one to update apm-data, the other to update the ingest pipeline).

One thing I notice is that we currently emit an `url.full`, which returns `url.String()` (which should be equivalent to original, except if there are parsing issues).
https://github.com/elastic/apm-server/blob/6d78528eb7e1ce4926ecb7caf1301d2439eaadcf/apmpackage/apm/data_stream/traces/fields/ecs.yml#L149-L164
https://github.com/elastic/apm-data/blob/main/model/modelpb/url.go#L43

The `uri_parts` processor doesn't seem to extract that field. So we will lose it.

**Comment by axw** [comment]
What I had in mind was that we would include the following in the model type, and in the documents send to Elasticsearch:
 - `url.original`, which may just be a URL path (e.g. from the HTTP request line)
 - `url.full`, which may be constructed from `url.original` and other attributes

Then in the ingest pipeline we would run `uri_parts` with `url.full` as input. Not sure how worthwhile this is. It would cut down the event size slightly, but add a little bit of processing overhead to the ingest pipeline.

**Comment by dmathieu** [comment]
So, as I am looking into this, I'm not sure it'd be really worth it.
When we [parse the URL](https://github.com/elastic/apm-data/blob/main/model/modelpb/url.go#L25), we also modify it based on the passed default hostname and default scheme.

In the case of intake ingestion, these two values are always blank. But in the case of OTLP, we use them if the `semconv.AttributeHTTPHost` or `semconv.AttributeHTTPScheme` attributes are passed.

In order to fill this data, we can't skip parsing the URL on our end, so if we rely on the `uri_parts` processor, we will be sending less data. But we will be parsing the URL twice, once on our end, and the second time within the processor.

**Comment by axw** [comment]
OK, I think we can forget this idea. Thanks for looking into it @dmathieu.
