### ISSUE TITLE
Remove processor fields

### ISSUE THREAD

**Issue by dmathieu** [elastic/apm-data#115]
The "processor" fields are a bit of a relic, and we should aim to remove them in the long term. With that in mind, I wonder if we should change the model a little bit so we can remove them from the apm-data codebase, and set the `processor.*` fields in our ingest pipelines, or by setting a value on `constant_keyword` fields where it makes sense.

e.g. for metrics, `processor.name` and `processor.event` are both always "metric", so we can update their field definitions to set the value in the mapping: https://github.com/elastic/apm-server/blob/23fb1577909836ebf45e65705df3fd560de5adb1/apmpackage/apm/data_stream/app_metrics/fields/fields.yml#L30-L35

IIANM the only exception to this is for the `apm.traces` and `apm.rum` data streams, where spans and transactions end up. These both have have `processor.name: transaction`, but they differ in `processor.event` (one is "span", one is "transaction"). Eventually spans and transactions should converge, but for now I think we could set the value in an ingest pipeline.

Maybe we could:
 - set [`event.kind`](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-kind) to either "span" or "transaction" in the apm-data code
 - update the `traces` ingest pipeline to use this to populate `processor.event`, and then remove `event.kind` since those values are not valid for `event.kind`

WDYT?

_Originally posted by @axw in https://github.com/elastic/apm-data/pull/58#discussion_r1228975554_

Related: #47.

**Comment by axw** [comment]
This will be addressed by https://github.com/elastic/apm-data/pull/79. There was a CI failure in publishing the requisite integration package change, so I haven't yet merged it.

**Comment by axw** [comment]
Closed by https://github.com/elastic/apm-data/pull/79
