### ISSUE TITLE
Consider using uint64 to store timestamps instead of timestamppb

### ISSUE THREAD

**Issue by lahsivjar** [elastic/apm-data#129]
If `APMEvents` is backed by vtproto's pool then `timestamppb` comes out as one of the most allocation heavy object. This was fixed in `apm-aggregation` by using `uint64` to encode timestamps. If `uint64` suits all our needs, we should consider promoting that package to `apm-data`: https://github.com/elastic/apm-aggregation/tree/main/aggregators/internal/timestamppb

**Comment by kruskall** [comment]
Closed by https://github.com/elastic/apm-data/pull/136
