### ISSUE TITLE
Use `modelpb.<Type>FromVTPool` wherever possible

### ISSUE THREAD

**Issue by marclop** [elastic/apm-data#130]
## Description

Since we added back pooling in #128, we should start using the pooled `modelpb.<Type>FromVTPool` wherever possible and indicate that clients should use `ReturnToVTPool` after they're done processing an event.

**Comment by marclop** [comment]
I started looking at changing at least the Intake/v2 decoding.

**Comment by marclop** [comment]
I started looking at this but stopped since I don't have the bandwidth to take this on ATM. Feel free to pick this up as desired.

**Comment by axw** [comment]
Is there anything left to do here?
