### ISSUE TITLE
invalid input for HTTPHeader: nil, numbers and maps

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-data#135]
Part of the ops KPI review, from the ecs logs:

```
decode error: data read error: v2.transactionRoot.Transaction: v2.transaction.Context: v2.context.Response: v2.contextResponse.Headers: invalid input for HTTPHeader: [<nil>]
```

```
decode error: data read error: v2.transactionRoot.Transaction: v2.transaction.Context: v2.context.Tags: Response: v2.contextResponse.Headers: invalid input for HTTPHeader: 301
```

```
decode error: data read error: v2.transactionRoot.Transaction: v2.transaction.Context: v2.context.Response: v2.contextResponse.Headers: invalid input for HTTPHeader: map[httponly:true path:/ samesite:Lax secure:true]
```

**Comment by kruskall** [comment]
`2.` and `3.` are not issues with apm-data. HTTP headers are supposed to be strings.

`1.` is a bit more complicated, we're handling nil at the root but not inside the slice:

See https://github.com/elastic/apm-data/blob/a636758ca08d02499994eb62121429153e3ae9c5/input/elasticapm/internal/modeldecoder/nullable/nullable.go#L131 and https://github.com/elastic/apm-data/blob/a636758ca08d02499994eb62121429153e3ae9c5/input/elasticapm/internal/modeldecoder/nullable/nullable.go#L136

- This is allowed: "foobar-header: null" 
- This is not allowed: "foobar-header: [ "a", null ]

Not sure what's the best approach here. @axw WDYT ?

**Comment by kruskall** [comment]
See https://github.com/elastic/apm-data/blob/a636758ca08d02499994eb62121429153e3ae9c5/input/elasticapm/internal/modeldecoder/nullable/nullable_test.go#L54

`"foobar-header: null"` will appear as if the header was not sent.

**Comment by axw** [comment]
> This is allowed: "foobar-header: null"
> This is not allowed: "foobar-header: [ "a", null ]

IMO we shouldn't accept either of them.
