### ISSUE TITLE
OTel mapping doesn't populate span.Db

### ISSUE THREAD

**Issue by stevejgordon** [elastic/apm-data#143]
Our code in [traces.go](https://github.com/elastic/apm-data/blob/main/input/otlp/traces.go#L740) doesn’t seem to map db attributes onto span.db, which should be reviewed and fixed.

**Comment by axw** [comment]
It's setting them here: https://github.com/elastic/apm-data/blob/455fb9f1280fa9dcb0ff4fa9ee08adb9a7970511/input/otlp/traces.go#L733

There's a test: https://github.com/elastic/apm-data/blob/455fb9f1280fa9dcb0ff4fa9ee08adb9a7970511/input/otlp/traces_test.go#L444-L486

**Comment by stevejgordon** [comment]
Thanks @axw. My bad; I misread the earlier code, and my actual issue is not what I thought. I will close this!
