### ISSUE TITLE
Map OTel `code.stacktrace` attribute top-level

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-data#177]
Once https://github.com/open-telemetry/semantic-conventions/pull/435 lands, we need to map the OTel `code.stacktrace` attribute top-level (instead of into labels) so we can display stacktraces on spans for OTel-based agents.

**Comment by SylvainJuge** [comment]
Implementation is split in two PRs:
- https://github.com/elastic/apm-data/pull/184 for `apm-data`
- https://github.com/elastic/apm-server/pull/12096 for `apm-server`
