### ISSUE TITLE
Map and store profiling stacktrace IDs on transactions

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-data#180]
https://github.com/elastic/apm-agent-java/issues/3409 will add the capability for transactions to store the IDs of stacktraces captured by the profiler during the corresponding. We will need to map and store these correctly in the APM server.

**Comment by simitt** [comment]
@JonasKunz are you (or someone from the otel data team) going to be able to work on this or do we need to schedule it for the Intake Service team?
