### ISSUE TITLE
remove async processing

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-data#193]
non-blocking ingest behaviour was added because of https://github.com/elastic/apm-server/issues/7872 to be used in the lambda extension.

It was never implemented and apm-server has improved since then. Recently there was some discussion around sync/async and it was proposed to remove it since we are not using it and it's just additional complexity.

cc @axw for feedback since you opened the initial issue

**Comment by axw** [comment]
Given that we never actually made use of it, and the general thrust behind treating OpenTelemetry as first class citizen (with no way to have those clients request such behaviour), I'm good with removing it.
