### ISSUE TITLE
service.target mapping missing for latest SemConv messaging attributes

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-data#284]
Currently, apm-data uses the OpenTelemetry attribute `messaging.destination` for messaging spans to derive `service.target`.
However, in the current semconv this attribute is now called [messaging.destination.name](https://opentelemetry.io/docs/specs/semconv/attributes-registry/messaging/).

Due to this mismatch, the service dependency graph is currently not correctly displayed for OpenTelemetry messaging spans reported for example via a current version of the OpenTelemetry Java agent.

We should update our mapping logic to use `messaging.destination.name`.

**Comment by kyungeunni** [comment]
apm-data still uses outdated semconv and there is a ticket describing how we'd like to keep up-to-date with the semconv changes : https://github.com/elastic/apm-data/issues/116
We can try to address the mentioned issue, or keep using the outdated `semconv` and manually map the new attribute.

**Comment by kyungeunni** [comment]
addressed by #298. APM Server will have this mapping from version 8.15([ref](https://github.com/elastic/apm-server/commit/a7c86ecccf99d42b242e0169d9d9f9ab09f4c849))
