### ISSUE TITLE
Derivation of the `span.type` from OTel data is indeterministic

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-data#43]
in OTel a single span can have a mix of attributes from different namespaces. For example, a span could have `db.*` attributes and at the same time `http.*` attributes. 

We use the logic of [this switch statement](https://github.com/elastic/apm-data/blob/0e8423572156bc44eea8b682c0dad1fa96d949cf/input/otlp/traces.go#L481) to determine the `foundSpanType` variable. This is done while iterating over all the attributes on a span. So basically the `last` attribute defines the actual `foundSpanType` and the corresponding mapping-logic below. This is indeterministic because we don't know the order of the span attributes.

We need a more explicit logic to derive the `span.type`.

**Comment by felixbarny** [comment]
Do you have a suggestion on the priority? I suppose `http.*` attributes would have the lowest priority as HTTP may be uses as a transport protocol for other types, such as DB or messaging. Are there any other priorities that we need to consider?
