### ISSUE TITLE
Review protobuf types before declaring it stable

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-data#47]
We should review protobuf fields to ensure we are using proper types.

- [x] validate signed/unsigned int usage
- [x] make sure ints have proper size (32/64)
- [x] improved storage for IPs (followup from https://github.com/elastic/apm-data/pull/42#discussion_r1213841328)

**Comment by axw** [comment]
We should also look at the encoding/decoding performance of maps, and compare against the array-of-structs approach: https://protobuf.dev/programming-guides/proto3/#backwards. We may want to do that after integrating into apm-server, in case it makes operating on the model types too painful.

**Comment by kruskall** [comment]
Also address `processor` field improvement: https://github.com/elastic/apm-data/pull/58#discussion_r1228975554

**Comment by axw** [comment]
I think we should probably not use the `Struct` type everywhere we're using it at the moment. e.g. HTTP headers should probably be `repeated Header`, where Header is a message comprising `string Key` and `repeated string Values`. Similar to Labels, but without Global.

**Comment by axw** [comment]
[SpanLink](https://github.com/elastic/apm-data/blob/5cae1b218218f79f28299d3201c7024f893105f1/model/proto/span.proto#L75C19-L78) should be updated to be a pair of string fields.

**Comment by axw** [comment]
Parent should be replaced with a ParentID field on the relevant types. Wherever we're using Span, Transaction, and Trace just to set the ID field (like in SpanLink) we should replace them with SpanID, TransactionID, TraceID.

**Comment by axw** [comment]
Same for Child, should be replaced with `repeated string`

**Comment by axw** [comment]
We should investigate whether we could use the Elasticsearch [`uri_parts`](https://www.elastic.co/guide/en/elasticsearch/reference/current/uri-parts-processor.html) ingest processor to parse URLs, and include only the full URL in the model types.

**Comment by dmathieu** [comment]
> [SpanLink](https://github.com/elastic/apm-data/blob/5cae1b218218f79f28299d3201c7024f893105f1/model/proto/span.proto#L75C19-L78) should be updated to be a pair of string fields.

I'm doubting a bit about that. OTLP has more to links that just a trace/span ID. Notably, it can have attributes.
https://github.com/open-telemetry/opentelemetry-proto/blob/c4dfbc51f3cd4089778555a2ac5d9bc093ed2956/opentelemetry/proto/trace/v1/trace.proto#L220-L239

**Comment by axw** [comment]
@dmathieu sorry for being unclear before, I meant to change the existing message from

```
message SpanLink {
  Trace trace = 1;
  Span span = 2;
}
```

to

```
message SpanLink {
  string trace_id = 1;
  string span_id = 2;
}
```

So still a message, but it shouldn't reference the full Trace/Span types. WDYT?

**Comment by dmathieu** [comment]
Improving IP storage: https://github.com/elastic/apm-data/pull/110

**Comment by kruskall** [comment]
@axw Could you advise on the possible types of certain fields ? Specifically:

- `error.exception.attributes`
- `error.custom`
- `stacktrace_frame.vars`
- `http.request.cookies`
- `http.request.var`
- `transaction.custom`

They are all `structpb.Struct` but I wonder whether they should be, e.g. http cookies are sent as key/value pairs, right ?

**Comment by axw** [comment]
@kruskall some of these are unclear, since they have _always_ been under specified.

> error.exception.attributes
> error.custom
> transaction.custom
> stacktrace_frame.vars

These are all arbitrary JSON.

> http.request.cookies

I think these should all be `map[string]string`, but I'm not 100% sure if any agents are sending structured/parsed cookie values. I think we could reasonably stringify the values coming from agents, if they're not already strings. I've asked for clarification in Slack.

> `http.request.var`

Did you mean `http.request.env`? I think this should also be `map[string]string`, and I have again asked for clarification.

**Comment by dmathieu** [comment]
Closing, as every action item in this issue has been acted upon. We can open new issues if something new arises.
