### ISSUE TITLE
Use enum value options during protobuf model mapping

### ISSUE THREAD

**Issue by kruskall** [elastic/apm-data#50]
From @axw 

> with the protobuf enums, is it possible to use options to control the string representation? https://protobuf.dev/programming-guides/proto3/#enum-value-options
> Then maybe we can avoid the manually maintained maps from names to enum values

**Comment by kruskall** [comment]
I might be missing something obvious but:
1. The snippet provided in the document does not seem to be valid (does not compile)
2. Even after fixing it, custom options do not allow to control the string representation of enums

cc @axw Could you clarify your initial comment ? Am I missing something ?

**Comment by axw** [comment]
@kruskall I don't know, it was a question in the first place. The docs made it look a bit like it was possible, but maybe not out of the box. So I guess let's forget about this and use handwritten mappings.
