### ISSUE TITLE
Add `span.id` field to transactions

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-data#82]
We want to converge span and transaction data models. For that, all transaction documents should also have a `span.id` field (where the field value is a copy of `transaction.id`).
This also will allow better correlation between logs and arbitrary spans (that are either spans or transactions) for OTel use cases.

OTel log records know about the `span.id` they belong to. However, if they are not tied to spans as SpanEvents, there's no way to tell whether the `span.id` in a log record belongs to a span document or a transaction. So, in case of transaction the correlation breaks, because we query for `span.id = XYZ` while transactions do not have a `span.id` field at all.

**Comment by SylvainJuge** [comment]
We have to cover the following types of documents / data flows:
- transaction documents from traces sent by agents (1)
- logs sent directly to apm-server by apm-agents (1)
- logs that are ingested through filebeat or similar (2)

For (1) it's mostly copying the value of `transaction.id` to `span.id`, however for (2) that might get a bit trickier as apm-data is not involved in writing those documents. In this case could we rely on an ingest pipeline or equivalent ?

**Comment by AlexanderWert** [comment]
> For (1) it's mostly copying the value of transaction.id to span.id, however for (2) that might get a bit trickier as apm-data is not involved in writing those documents. In this case could we rely on an ingest pipeline or equivalent ?

I'd propose to ignore (2) for now. 

(2) could be solved by apm-agents / logging-libraries by always writing a `span.id`, even for logs relate to a transaction (in that case `span.id = transaction.id`).

**Comment by SylvainJuge** [comment]
Very good point for (2), this provides a good reason for doing this change across all APM agents.
