### ISSUE TITLE
Provide enablement material

### ISSUE THREAD

**Issue by simitt** [elastic/apm-data#9]
We want to onboard apm-agent developers to this repository, to be able to work on open-telemetry mappings and to add new fields to the Intake API and processing. 

For enablement we need to 
- add a high level overview over data flow and processing
- provide a recorded video with a code-walkthrough
- document which code changes, make commands, approval test adoptions, etc. are required for adding a new field; link to a reference PR
- document which code changes are required for adding or changing open telemetry mappings
- show which steps are required in the APM Server code base to update

**Comment by simitt** [comment]
@axw are you still intending on providing a short code walkthrough video? Otherwise I think we should close this out.

**Comment by axw** [comment]
@simitt maybe eventually, but not right now. It'll probably be invalidated by the coming protobuf changes.
