### ISSUE TITLE
ci: Run micro-bechmarks on every commit and PR

### ISSUE THREAD

**Issue by marclop** [elastic/apm-data#97]
## Description

APM Data is a crucial module, rather than just rely on the APM Server benchmarks to detect potential performance regressions, run the Go micro benchmarks for every commit and in every PR, so any regressions (and performance improvements) can be caught early

**Comment by simitt** [comment]
@cachedout can the automation team drive this?

**Comment by simitt** [comment]
@cachedout friendly reminder, do you think the eng.productivity team could take this on?

**Comment by cachedout** [comment]
Apologies for missing this earlier. Yes, certainly. I've added it to our queue.

**Comment by simitt** [comment]
@cachedout is there an ETA for this? It seems that this is part of your board, but not yet scheduled (afaics).

**Comment by v1v** [comment]
IIUC, you want to run `go test -bench=. -count=10` as explained https://pkg.go.dev/golang.org/x/perf/cmd/benchstat#hdr-Example but using the existing `micro-benchmark` pool? Or are you happy to use the existing ephemeral GitHub runners? 

If it requires the `micro-benchmark` then we are at the moment blocked by some security concerns. The current pool of micro-benchmarks are defined in Buildkite, and to simplify how to use them we have provided a GitHub action integration with Buildkite, but it requires some GitHub secret access and running on forker PRs we cannot use any secrets.

**Comment by simitt** [comment]
IMO github runners are fine; the objective is to run the benchmark tests on every PR and commit to be aware of regressions.

**Comment by v1v** [comment]
Thanks Silvia, one more question:

* do we need to compare the output with a previous run? Or that's not required for the time being but something to be done in a follow up?

Otherwise https://github.com/elastic/apm-data/pull/168 is the proposal, so we can iterate on this if needed

**Comment by v1v** [comment]
PR has been merged and https://github.com/elastic/apm-data/runs/17814931419 is one of the examples with the report.

It's possible to configure the thresholds and the status of the build as explained in https://github.com/elastic/apm-data/pull/170#discussion_r1361316159. Let me know if you want to change the settings to be less relaxed and notify if a big variation in the benchmarks with some failures.

I'll close this now, feel free to reach me if you need something else. 🙏

**Comment by v1v** [comment]
I've just found wrongly that `pull_request` does not allow to create GitHub checks on forked PRs, hence https://github.com/elastic/apm-data/pull/173 is the alternative to visualise the micro-benchmarks when running on forked PRs. 


![Image](https://github.com/elastic/apm-data/assets/2871786/a09626aa-cf9f-4edc-b23c-844db20a6ee5)
